### ISSUE TITLE
delete ?

### ISSUE THREAD

**Issue by kapouer** [Irrelon/irrelon-path#1]
Hi,

`.delete(obj, path)`

would be cool.
Thanks !

**Comment by Irrelon** [comment]
Hey ya,

You can achieve the same thing via `set(obj, path, undefined);`

I guess we *could* put a delete alias in to call set but that also raises issues because delete is a reserved word so the function would have to be called something else!

**Comment by Irrelon** [comment]
Actually we could call it `unset()` ?

**Comment by kapouer** [comment]
Problem is that
```
> var obj = {test:1}
undefined
> obj.test = undefined
undefined
> obj.hasOwnProperty('test')
true
```

**Comment by Irrelon** [comment]
Ahh gotcha. You actually want to remove the key from the object not just clear the value. Makes sense, totally easy to add this.

What do you think about the name of the function? Like I said, `unset()` is an option. Any other ideas that are not `delete()`?

**Comment by kapouer** [comment]
set/unset is fine for me, as well as clear, del, remove.

**Comment by Irrelon** [comment]
This was added as unSet(). :)
