### ISSUE TITLE
The "unSet" function does not handle strings contained '.' correctly

### ISSUE THREAD

**Issue by charles-zh** [Irrelon/irrelon-path#7]
**Describe the bug**

** Version of Irrelon Path **
4.2.2 in npmjs and 4.2.3 in github.com

**To Reproduce**

```
const testJson = {
    "root": {
        "new.file": "demo content",
    }
};

const path = 'root' + '.' + escape('new.file');
unSet(testJson, path);
console.log(testJson);

```
**Expected behavior**
Remove that "new.file" key in the json string.

**fix:**

in Path.js file, unSet function:

newObj.hasOwnProperty(...)
Call unEscape function before passing in parameters

```
	// Path has no dot-notation, set key/value
	if (isNonCompositePath(internalPath)) {
		if (newObj.hasOwnProperty(unEscape(internalPath))) {
			delete newObj[options.transformKey(unEscape(internalPath))];
			return newObj;
		}
		
		tracking.returnOriginal = true;
		return obj;
	}

```

**Comment by Irrelon** [comment]
Hey, thanks for the thorough analysis. Looks like the escaped path coverage is poor in a number of functions. I'll do a sweep and add unit tests to check escaping across the board and then apply a fix once it's ready. Appreciate the help to make the library better! :)

**Comment by Irrelon** [comment]
Thanks for your help in identifying this bug, the latest version has fixed this, new tests in place and passing.
